2024-11-19 00:29:37,240 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-11-19 00:29:37,362 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @more_actions_bot id=5782161283 - 'More Actions Bot'
2024-11-19 00:29:44,677 - [ERROR] - src.repository - (repository.py).create(63) - (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1425820937) already exists.
[SQL: INSERT INTO users (id, username, first_name, language_code, is_premium, is_bot, is_blocked, ref_id) VALUES ($1::BIGINT, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::BOOLEAN, $6::BOOLEAN, $7::BOOLEAN, $8::BIGINT) RETURNING users.id, users.username, users.first_name, users.language_code, users.is_premium, users.is_bot, users.is_blocked, users.ref_id, users.datetime_first, users.datetime_last]
[parameters: (1425820937, 'acruxtech', 'Vladimir', 'en', True, False, False, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-11-19 00:29:44,685 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=427346193 is handled. Duration 1110 ms by bot id=5782161283
2024-11-19 00:29:48,613 - [ERROR] - src.repository - (repository.py).create(63) - (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1425820937) already exists.
[SQL: INSERT INTO users (id, username, first_name, language_code, is_premium, is_bot, is_blocked, ref_id) VALUES ($1::BIGINT, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::BOOLEAN, $6::BOOLEAN, $7::BOOLEAN, $8::BIGINT) RETURNING users.id, users.username, users.first_name, users.language_code, users.is_premium, users.is_bot, users.is_blocked, users.ref_id, users.datetime_first, users.datetime_last]
[parameters: (1425820937, 'acruxtech', 'Vladimir', 'en', True, False, False, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-11-19 00:29:48,621 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=427346194 is handled. Duration 638 ms by bot id=5782161283
2024-11-19 00:29:49,955 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=427346195 is handled. Duration 106 ms by bot id=5782161283
2024-11-19 00:29:52,556 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=427346196 is handled. Duration 234 ms by bot id=5782161283
2024-11-19 00:29:59,298 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=427346197 is not handled. Duration 203 ms by bot id=5782161283
2024-11-19 00:29:59,298 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=427346197 by bot id=5782161283
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/src/middlewares/limit.py", line 40, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/venv/lib64/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/src/handlers/basic.py", line 157, in get_scammer_username
    await create_media(scammer, proof, message, bot, msg)
  File "/home/acruxtech/Documents/work/other/anti-scam-tg-bot/src/utils/media.py", line 12, in create_media
    media = await media_repository.get_last_true_proofs(scammer.id)
                                                        ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
